server {
    listen 80;
    
    # Root directory nơi Nginx sẽ đọc các file tĩnh (build từ React)
    root /usr/share/nginx/html;
    index index.html index.htm;

    # Quan trọng cho React Router: Mọi request đều trả về index.html để React xử lý điều hướng
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Tối ưu cache cho các file tĩnh
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
}
