# Alembic configuration file
# Đây là file cấu hình bắt buộc nếu bạn dùng thư viện Alembic để quản lý migration database.
# Bạn sẽ cần chỉ định sqlalchemy.url trong này, hoặc ghi đè url động trong env.py
[alembic]
script_location = alembic
sqlalchemy.url = postgresql://postgres:postgres@localhost/web_base

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
